import vueParser from "vue-eslint-parser"
import vuePlugin from "eslint-plugin-vue"
import tsParser from "@typescript-eslint/parser"
import tsPlugin from "@typescript-eslint/eslint-plugin"
import prettierPlugin from "eslint-plugin-prettier"
import globals from "globals"

export default [
	{
		files: ["src/**/*.{ts,vue}"],
		ignores: ["dist/**", "node_modules/**"],
		languageOptions: {
			parser: vueParser,
			parserOptions: {
				parser: tsParser,
				extraFileExtensions: [".vue"],
				ecmaVersion: "latest",
				sourceType: "module",
				project: ["./tsconfig.json"],
				tsconfigRootDir: process.cwd(),
				warnOnUnsupportedTypeScriptVersion: true,
			},
			globals: {
				...globals.browser,
				...globals.es2021,
			},
		},
		plugins: {
			vue: vuePlugin,
			"@typescript-eslint": tsPlugin,
			prettier: prettierPlugin,
		},
		rules: {
			eqeqeq: ["error", "always"],
			indent: "off",
			"no-debugger": "error",
			"no-duplicate-imports": "error",
			"no-implied-eval": "error",
			"no-implicit-coercion": "error",
			"no-new-func": "error",
			"no-prototype-builtins": "error",
			"no-unreachable": "error",
			"no-unused-vars": "error",
			"no-useless-call": "error",
			"no-useless-concat": "error",
			"no-var": "error",
			"no-undef": "error",
			"prefer-const": "error",
			"prefer-object-spread": "error",
			"prefer-regex-literals": "error",
			"prettier/prettier": ["error"],
			"no-return-await": "error",
			"no-throw-literal": "error",
			"no-unneeded-ternary": "error",
			"no-useless-return": "error",
			"prefer-promise-reject-errors": "error",
			"require-await": "error",
			"prefer-template": "error",
			"no-extra-bind": "error",
			"no-useless-escape": "error",
			"no-self-compare": "error",

			"@typescript-eslint/await-thenable": "error",
			"@typescript-eslint/consistent-type-definitions": [
				"error",
				"interface",
			],
			"@typescript-eslint/consistent-type-imports": "error",
			"@typescript-eslint/explicit-function-return-type": [
				"error",
				{ allowExpressions: false },
			],
			"@typescript-eslint/no-empty-function": "error",
			"@typescript-eslint/no-explicit-any": "error",
			"@typescript-eslint/no-floating-promises": "error",
			"@typescript-eslint/no-inferrable-types": "error",
			"@typescript-eslint/no-misused-promises": "error",
			"@typescript-eslint/no-non-null-assertion": "error",
			"@typescript-eslint/no-unnecessary-condition": [
				"error",
				{ allowConstantLoopConditions: false },
			],
			"@typescript-eslint/no-unnecessary-type-assertion": "error",
			"@typescript-eslint/no-unused-expressions": "error",
			"@typescript-eslint/no-unused-vars": [
				"error",
				{ argsIgnorePattern: "^_" },
			],
			"@typescript-eslint/no-var-requires": "error",
			"@typescript-eslint/strict-boolean-expressions": "error",
			"@typescript-eslint/no-duplicate-enum-values": "error",
			"@typescript-eslint/no-extra-non-null-assertion": "error",
			"@typescript-eslint/no-for-in-array": "error",
			"@typescript-eslint/prefer-for-of": "error",
			"@typescript-eslint/prefer-optional-chain": "error",
			"@typescript-eslint/prefer-nullish-coalescing": "error",
			"@typescript-eslint/restrict-plus-operands": "error",
			"@typescript-eslint/unbound-method": "error",

			"vue/html-indent": "off",
			"vue/multi-word-component-names": "off",
			"vue/no-async-in-computed-properties": "error",
			"vue/no-mutating-props": "error",
			"vue/no-ref-as-operand": "error",
			"vue/no-side-effects-in-computed-properties": "error",
			"vue/no-unused-components": "error",
			"vue/no-unused-properties": [
				"error",
				{ groups: ["props", "data", "computed", "methods"] },
			],
			"vue/no-unused-vars": "error",
			"vue/no-v-html": "off",
			"vue/no-v-text": "error",
			"vue/require-default-prop": "error",
			"vue/require-explicit-emits": "error",
			"vue/require-prop-types": "error",
			"vue/script-indent": "off",
			"vue/no-use-v-if-with-v-for": "error",
			"vue/no-template-key": "error",
			"vue/no-useless-template-attributes": "error",
			"vue/no-reserved-component-names": "error",
			"vue/require-name-property": "error",

			"no-console": "off",
			"no-alert": "off",
			"no-shadow": "error",
			"no-constant-condition": ["error", { checkLoops: true }],
			"no-empty": ["error", { allowEmptyCatch: false }],
			"no-extra-semi": "error",
			"no-multi-assign": "error",
			"no-nested-ternary": "error",
			"no-useless-catch": "error",
			"no-useless-rename": "error",
			"no-useless-return": "error",
			"prefer-arrow-callback": "error",
			"prefer-rest-params": "error",
			"prefer-spread": "error",
			"@typescript-eslint/array-type": [
				"error",
				{ default: "array-simple" },
			],
			"@typescript-eslint/explicit-member-accessibility": [
				"error",
				{ accessibility: "explicit" },
			],
			"@typescript-eslint/no-extraneous-class": "error",
			"@typescript-eslint/no-useless-empty-export": "error",
			"vue/valid-v-slot": "error",
			"vue/no-template-shadow": "error",
			"vue/no-useless-v-bind": "error",
			"vue/prefer-true-attribute-shorthand": "error",
		},
	},
	{
		files: ["src/**/*.js"],
		ignores: ["dist/**", "node_modules/**"],
		languageOptions: {
			ecmaVersion: "latest",
			sourceType: "module",
			globals: {
				...globals.browser,
				...globals.es2021,
			},
		},
		plugins: {
			prettier: prettierPlugin,
		},
		rules: {
			eqeqeq: ["error", "always"],
			"no-debugger": "error",
			"no-duplicate-imports": "error",
			"no-unreachable": "error",
			"no-unused-vars": "error",
			"no-undef": "error",
			"no-var": "error",
			"prefer-const": "error",
			"prettier/prettier": ["error"],
			"no-return-await": "error",
			"no-throw-literal": "error",
			"no-unneeded-ternary": "error",
			"no-useless-return": "error",
			"prefer-promise-reject-errors": "error",
			"require-await": "error",
			"prefer-template": "error",
			"no-extra-bind": "error",
			"no-useless-escape": "error",
			"no-self-compare": "error",

			"no-console": "off",
			"no-alert": "off",
			"no-shadow": "error",
			"no-constant-condition": ["error", { checkLoops: true }],
			"no-empty": ["error", { allowEmptyCatch: false }],
			"no-extra-semi": "error",
			"no-multi-assign": "error",
			"no-nested-ternary": "error",
			"no-useless-catch": "error",
			"no-useless-rename": "error",
			"prefer-arrow-callback": "error",
			"prefer-rest-params": "error",
			"prefer-spread": "error",
		},
	},
]
