image: alpine/edge
packages:
  - golangci-lint
  - go
  - npm
tasks:
  - prepare: |
      cd cca
      ./prepare
  - build: |
      cd cca
      ./build
  - lint: |
      cd cca
      golangci-lint run .
