worker_processes auto;
worker_rlimit_nofile 65535;
pid /tmp/nginx.pid;
error_log /dev/stderr warn;

events {
	worker_connections 8192;
}

http {
	access_log off;
	client_max_body_size 100m;

	map $http_upgrade $connection_upgrade {
		default upgrade;
		'' '';
	}

	upstream cca_backend {
		server 127.0.0.1:8193;
		keepalive 256;
	}

	server {
		listen 0.0.0.0:8192;

		location / {
			proxy_pass http://cca_backend;
			proxy_http_version 1.1;
			proxy_set_header Host $http_host;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection $connection_upgrade;
			proxy_read_timeout 70s;
			proxy_send_timeout 10s;
		}
	}
}
