// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package db

import (
	"context"
)

const deleteCategory = `-- name: DeleteCategory :execrows
DELETE FROM categories WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCategory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCategories = `-- name: GetCategories :many
SELECT id, name FROM categories ORDER BY id
`

func (q *Queries) GetCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, getCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newCategory = `-- name: NewCategory :exec
INSERT INTO categories (id, name) VALUES ($1, $2)
`

type NewCategoryParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) NewCategory(ctx context.Context, arg NewCategoryParams) error {
	_, err := q.db.Exec(ctx, newCategory, arg.ID, arg.Name)
	return err
}

const renameCategory = `-- name: RenameCategory :execrows
UPDATE categories SET name = $2 WHERE id = $1
`

type RenameCategoryParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) RenameCategory(ctx context.Context, arg RenameCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, renameCategory, arg.ID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
