// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: courses.sql

package db

import (
	"context"
)

const createCourse = `-- name: CreateCourse :exec
SELECT create_course($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11,
	$12, $13, $14)
`

type CreateCourseParams struct {
	PCourseID     string     `json:"p_course_id"`
	PName         string     `json:"p_name"`
	PDescription  string     `json:"p_description"`
	PCategoryID   string     `json:"p_category_id"`
	PTeacher      string     `json:"p_teacher"`
	PTeacherEmail string     `json:"p_teacher_email"`
	PLocation     string     `json:"p_location"`
	PTerm         string     `json:"p_term"`
	PCost         string     `json:"p_cost"`
	PInviteOnly   bool       `json:"p_invite_only"`
	PMaxStudents  int64      `json:"p_max_students"`
	PPeriodIds    []string   `json:"p_period_ids"`
	PLegalSexes   []LegalSex `json:"p_legal_sexes"`
	PGradeIds     []string   `json:"p_grade_ids"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) error {
	_, err := q.db.Exec(ctx, createCourse,
		arg.PCourseID,
		arg.PName,
		arg.PDescription,
		arg.PCategoryID,
		arg.PTeacher,
		arg.PTeacherEmail,
		arg.PLocation,
		arg.PTerm,
		arg.PCost,
		arg.PInviteOnly,
		arg.PMaxStudents,
		arg.PPeriodIds,
		arg.PLegalSexes,
		arg.PGradeIds,
	)
	return err
}

const deleteCourse = `-- name: DeleteCourse :exec
SELECT delete_course($1)
`

func (q *Queries) DeleteCourse(ctx context.Context, pCourseID string) error {
	_, err := q.db.Exec(ctx, deleteCourse, pCourseID)
	return err
}

const getCourseCountsByIDs = `-- name: GetCourseCountsByIDs :many
SELECT v.id, v.current_students
FROM v_courses v
WHERE v.id = ANY ($1::TEXT[])
`

type GetCourseCountsByIDsRow struct {
	ID              string `json:"id"`
	CurrentStudents int64  `json:"current_students"`
}

// The realtime mirror's refresh: the enrollee count of the courses
// that have just been written, and only those. Reads current_students
// from v_courses so the browser's count and the capacity rule cannot
// come from two different definitions.
func (q *Queries) GetCourseCountsByIDs(ctx context.Context, courseIds []string) ([]GetCourseCountsByIDsRow, error) {
	rows, err := q.db.Query(ctx, getCourseCountsByIDs, courseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCourseCountsByIDsRow
	for rows.Next() {
		var i GetCourseCountsByIDsRow
		if err := rows.Scan(&i.ID, &i.CurrentStudents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCourses = `-- name: GetCourses :many
SELECT id, name, description, category_id, teacher, teacher_email, location, term, cost, max_students, invite_only, current_students, period_ids, allowed_legal_sexes, allowed_grade_ids FROM v_courses ORDER BY id
`

func (q *Queries) GetCourses(ctx context.Context) ([]VCourse, error) {
	rows, err := q.db.Query(ctx, getCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VCourse
	for rows.Next() {
		var i VCourse
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CategoryID,
			&i.Teacher,
			&i.TeacherEmail,
			&i.Location,
			&i.Term,
			&i.Cost,
			&i.MaxStudents,
			&i.InviteOnly,
			&i.CurrentStudents,
			&i.PeriodIds,
			&i.AllowedLegalSexes,
			&i.AllowedGradeIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameCourseID = `-- name: RenameCourseID :execrows
UPDATE courses SET id = $2 WHERE id = $1
`

type RenameCourseIDParams struct {
	ID   string `json:"id"`
	ID_2 string `json:"id_2"`
}

func (q *Queries) RenameCourseID(ctx context.Context, arg RenameCourseIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, renameCourseID, arg.ID, arg.ID_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCourse = `-- name: UpdateCourse :exec
SELECT update_course($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11,
	$12, $13, $14, $15)
`

type UpdateCourseParams struct {
	PCourseID     string     `json:"p_course_id"`
	PName         string     `json:"p_name"`
	PDescription  string     `json:"p_description"`
	PCategoryID   string     `json:"p_category_id"`
	PTeacher      string     `json:"p_teacher"`
	PTeacherEmail string     `json:"p_teacher_email"`
	PLocation     string     `json:"p_location"`
	PTerm         string     `json:"p_term"`
	PCost         string     `json:"p_cost"`
	PInviteOnly   bool       `json:"p_invite_only"`
	PMaxStudents  int64      `json:"p_max_students"`
	PPeriodIds    []string   `json:"p_period_ids"`
	PLegalSexes   []LegalSex `json:"p_legal_sexes"`
	PGradeIds     []string   `json:"p_grade_ids"`
	PAccept       []string   `json:"p_accept"`
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) error {
	_, err := q.db.Exec(ctx, updateCourse,
		arg.PCourseID,
		arg.PName,
		arg.PDescription,
		arg.PCategoryID,
		arg.PTeacher,
		arg.PTeacherEmail,
		arg.PLocation,
		arg.PTerm,
		arg.PCost,
		arg.PInviteOnly,
		arg.PMaxStudents,
		arg.PPeriodIds,
		arg.PLegalSexes,
		arg.PGradeIds,
		arg.PAccept,
	)
	return err
}

const upsertCourses = `-- name: UpsertCourses :exec
SELECT upsert_courses($1, $2)
`

type UpsertCoursesParams struct {
	PCourses []byte   `json:"p_courses"`
	PAccept  []string `json:"p_accept"`
}

func (q *Queries) UpsertCourses(ctx context.Context, arg UpsertCoursesParams) error {
	_, err := q.db.Exec(ctx, upsertCourses, arg.PCourses, arg.PAccept)
	return err
}
