// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enrollments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const enrollmentViolations = `-- name: EnrollmentViolations :many
SELECT rule, code, other_course_id, period_id, detail
FROM enrollment_violations($1, $2, $3, $4)
`

type EnrollmentViolationsParams struct {
	PStudentID          string   `json:"p_student_id"`
	PCourseID           string   `json:"p_course_id"`
	PCountsTowardBudget bool     `json:"p_counts_toward_budget"`
	PDisregardCourseIds []string `json:"p_disregard_course_ids"`
}

type EnrollmentViolationsRow struct {
	Rule          pgtype.Text `json:"rule"`
	Code          pgtype.Text `json:"code"`
	OtherCourseID pgtype.Text `json:"other_course_id"`
	PeriodID      pgtype.Text `json:"period_id"`
	Detail        pgtype.Text `json:"detail"`
}

func (q *Queries) EnrollmentViolations(ctx context.Context, arg EnrollmentViolationsParams) ([]EnrollmentViolationsRow, error) {
	rows, err := q.db.Query(ctx, enrollmentViolations,
		arg.PStudentID,
		arg.PCourseID,
		arg.PCountsTowardBudget,
		arg.PDisregardCourseIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnrollmentViolationsRow
	for rows.Next() {
		var i EnrollmentViolationsRow
		if err := rows.Scan(
			&i.Rule,
			&i.Code,
			&i.OtherCourseID,
			&i.PeriodID,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnrollments = `-- name: GetEnrollments :many
SELECT student_id, student_name, grade_id, course_id, course_name, student_droppable, counts_toward_budget FROM v_enrollments ORDER BY student_id, course_id
`

func (q *Queries) GetEnrollments(ctx context.Context) ([]VEnrollment, error) {
	rows, err := q.db.Query(ctx, getEnrollments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VEnrollment
	for rows.Next() {
		var i VEnrollment
		if err := rows.Scan(
			&i.StudentID,
			&i.StudentName,
			&i.GradeID,
			&i.CourseID,
			&i.CourseName,
			&i.StudentDroppable,
			&i.CountsTowardBudget,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnrollmentsByStudent = `-- name: GetEnrollmentsByStudent :many
SELECT student_id, student_name, grade_id, course_id, course_name, student_droppable, counts_toward_budget FROM v_enrollments WHERE student_id = $1 ORDER BY course_id
`

func (q *Queries) GetEnrollmentsByStudent(ctx context.Context, studentID string) ([]VEnrollment, error) {
	rows, err := q.db.Query(ctx, getEnrollmentsByStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VEnrollment
	for rows.Next() {
		var i VEnrollment
		if err := rows.Scan(
			&i.StudentID,
			&i.StudentName,
			&i.GradeID,
			&i.CourseID,
			&i.CourseName,
			&i.StudentDroppable,
			&i.CountsTowardBudget,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnrollmentsExport = `-- name: GetEnrollmentsExport :many
SELECT student_id, student_name, grade_id, legal_sex,
	course_id, course_name, term, COALESCE(period_id, '')::TEXT AS period_id,
	student_droppable, counts_toward_budget
FROM v_export_enrollments
ORDER BY student_id, course_id, period_sort_order NULLS FIRST, period_id
`

type GetEnrollmentsExportRow struct {
	StudentID          string   `json:"student_id"`
	StudentName        string   `json:"student_name"`
	GradeID            string   `json:"grade_id"`
	LegalSex           LegalSex `json:"legal_sex"`
	CourseID           string   `json:"course_id"`
	CourseName         string   `json:"course_name"`
	Term               string   `json:"term"`
	PeriodID           string   `json:"period_id"`
	StudentDroppable   bool     `json:"student_droppable"`
	CountsTowardBudget bool     `json:"counts_toward_budget"`
}

// An unscheduled course has no period, which the spreadsheet wants as
// an empty cell rather than a NULL; absence is ” here as everywhere.
func (q *Queries) GetEnrollmentsExport(ctx context.Context) ([]GetEnrollmentsExportRow, error) {
	rows, err := q.db.Query(ctx, getEnrollmentsExport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEnrollmentsExportRow
	for rows.Next() {
		var i GetEnrollmentsExportRow
		if err := rows.Scan(
			&i.StudentID,
			&i.StudentName,
			&i.GradeID,
			&i.LegalSex,
			&i.CourseID,
			&i.CourseName,
			&i.Term,
			&i.PeriodID,
			&i.StudentDroppable,
			&i.CountsTowardBudget,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const placeEnrollments = `-- name: PlaceEnrollments :exec
SELECT place_enrollments($1, $2, $3, $4, $5)
`

type PlaceEnrollmentsParams struct {
	PCourseID           string   `json:"p_course_id"`
	PStudentIds         []string `json:"p_student_ids"`
	PStudentDroppable   bool     `json:"p_student_droppable"`
	PCountsTowardBudget bool     `json:"p_counts_toward_budget"`
	PAccept             []string `json:"p_accept"`
}

func (q *Queries) PlaceEnrollments(ctx context.Context, arg PlaceEnrollmentsParams) error {
	_, err := q.db.Exec(ctx, placeEnrollments,
		arg.PCourseID,
		arg.PStudentIds,
		arg.PStudentDroppable,
		arg.PCountsTowardBudget,
		arg.PAccept,
	)
	return err
}

const removeEnrollments = `-- name: RemoveEnrollments :exec
SELECT remove_enrollments($1, $2)
`

type RemoveEnrollmentsParams struct {
	PCourseID   string   `json:"p_course_id"`
	PStudentIds []string `json:"p_student_ids"`
}

func (q *Queries) RemoveEnrollments(ctx context.Context, arg RemoveEnrollmentsParams) error {
	_, err := q.db.Exec(ctx, removeEnrollments, arg.PCourseID, arg.PStudentIds)
	return err
}

const selfDrop = `-- name: SelfDrop :exec
SELECT self_drop($1, $2)
`

type SelfDropParams struct {
	PStudentID string `json:"p_student_id"`
	PCourseID  string `json:"p_course_id"`
}

func (q *Queries) SelfDrop(ctx context.Context, arg SelfDropParams) error {
	_, err := q.db.Exec(ctx, selfDrop, arg.PStudentID, arg.PCourseID)
	return err
}

const selfEnroll = `-- name: SelfEnroll :exec
SELECT self_enroll($1, $2)
`

type SelfEnrollParams struct {
	PStudentID string `json:"p_student_id"`
	PCourseID  string `json:"p_course_id"`
}

func (q *Queries) SelfEnroll(ctx context.Context, arg SelfEnrollParams) error {
	_, err := q.db.Exec(ctx, selfEnroll, arg.PStudentID, arg.PCourseID)
	return err
}

const selfSwap = `-- name: SelfSwap :exec
SELECT self_swap($1, $2, $3)
`

type SelfSwapParams struct {
	PStudentID    string   `json:"p_student_id"`
	POldCourseIds []string `json:"p_old_course_ids"`
	PCourseID     string   `json:"p_course_id"`
}

func (q *Queries) SelfSwap(ctx context.Context, arg SelfSwapParams) error {
	_, err := q.db.Exec(ctx, selfSwap, arg.PStudentID, arg.POldCourseIds, arg.PCourseID)
	return err
}

const setEnrollmentPolicy = `-- name: SetEnrollmentPolicy :exec
SELECT set_enrollment_policy($1, $2, $3, $4, $5)
`

type SetEnrollmentPolicyParams struct {
	PCourseID           string   `json:"p_course_id"`
	PStudentIds         []string `json:"p_student_ids"`
	PStudentDroppable   bool     `json:"p_student_droppable"`
	PCountsTowardBudget bool     `json:"p_counts_toward_budget"`
	PAccept             []string `json:"p_accept"`
}

func (q *Queries) SetEnrollmentPolicy(ctx context.Context, arg SetEnrollmentPolicyParams) error {
	_, err := q.db.Exec(ctx, setEnrollmentPolicy,
		arg.PCourseID,
		arg.PStudentIds,
		arg.PStudentDroppable,
		arg.PCountsTowardBudget,
		arg.PAccept,
	)
	return err
}

const studentCourseViolations = `-- name: StudentCourseViolations :many
SELECT course_id, rule, code, other_course_id, period_id, detail
FROM student_course_violations($1, $2)
`

type StudentCourseViolationsParams struct {
	PStudentID          string `json:"p_student_id"`
	PCountsTowardBudget bool   `json:"p_counts_toward_budget"`
}

type StudentCourseViolationsRow struct {
	CourseID      pgtype.Text `json:"course_id"`
	Rule          pgtype.Text `json:"rule"`
	Code          pgtype.Text `json:"code"`
	OtherCourseID pgtype.Text `json:"other_course_id"`
	PeriodID      pgtype.Text `json:"period_id"`
	Detail        pgtype.Text `json:"detail"`
}

func (q *Queries) StudentCourseViolations(ctx context.Context, arg StudentCourseViolationsParams) ([]StudentCourseViolationsRow, error) {
	rows, err := q.db.Query(ctx, studentCourseViolations, arg.PStudentID, arg.PCountsTowardBudget)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StudentCourseViolationsRow
	for rows.Next() {
		var i StudentCourseViolationsRow
		if err := rows.Scan(
			&i.CourseID,
			&i.Rule,
			&i.Code,
			&i.OtherCourseID,
			&i.PeriodID,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
