// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: grades.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeGradeWindowNow = `-- name: CloseGradeWindowNow :execrows
UPDATE grades SET closes_at = now()
WHERE id = $1::entity_id
	AND EXISTS (SELECT 1 FROM v_grades v
		WHERE v.id = grades.id AND v.is_open)
`

// Closing writes closes_at and leaves opens_at alone: that is when the
// window ran, and once it is gone the card can no longer say what
// happened, only that nothing is happening.
//
// Guarded on v_grades.is_open rather than on a bound comparison
// written out again here. Openness has one definition and this is a
// caller of it, not a second author of it — and getting it slightly
// wrong is not hypothetical: guarding on opens_at < now() alone also
// matches a window that opened and closed yesterday, so closing an
// already-shut grade overwrote the record of when it really ran.
//
// The guard also makes closes_at > opens_at hold by construction: a
// window that is open began before now. Zero rows means there was
// nothing to close, which is a true answer worth giving rather than an
// error; a window merely scheduled to open later is cancelled by
// clearing opens_at, not by closing it.
// Cast for the same reason as the opener above: the domain does not
// survive inference past the subquery, and an id that is never NULL
// should not travel as one that might be.
func (q *Queries) CloseGradeWindowNow(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, closeGradeWindowNow, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteGrade = `-- name: DeleteGrade :execrows
DELETE FROM grades WHERE id = $1
`

func (q *Queries) DeleteGrade(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGrade, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGradeRequirements = `-- name: GetGradeRequirements :many
SELECT id, grade_id, min_period_count, category_ids FROM v_grade_requirements ORDER BY grade_id, id
`

func (q *Queries) GetGradeRequirements(ctx context.Context) ([]VGradeRequirement, error) {
	rows, err := q.db.Query(ctx, getGradeRequirements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VGradeRequirement
	for rows.Next() {
		var i VGradeRequirement
		if err := rows.Scan(
			&i.ID,
			&i.GradeID,
			&i.MinPeriodCount,
			&i.CategoryIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGrades = `-- name: GetGrades :many
SELECT id, name, opens_at, closes_at, is_open, max_budgeted_periods, min_distinct_categories, sort_order FROM v_grades ORDER BY sort_order, id
`

func (q *Queries) GetGrades(ctx context.Context) ([]VGrade, error) {
	rows, err := q.db.Query(ctx, getGrades)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VGrade
	for rows.Next() {
		var i VGrade
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OpensAt,
			&i.ClosesAt,
			&i.IsOpen,
			&i.MaxBudgetedPeriods,
			&i.MinDistinctCategories,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newGrade = `-- name: NewGrade :exec
INSERT INTO grades
	(id, name, opens_at, closes_at,
	 max_budgeted_periods, min_distinct_categories, sort_order)
SELECT $1, $2, NULL, NULL,
	$3, $4,
	COALESCE(MAX(sort_order), 0) + 1
FROM grades
`

type NewGradeParams struct {
	ID                    string      `json:"id"`
	Name                  string      `json:"name"`
	MaxBudgetedPeriods    pgtype.Int8 `json:"max_budgeted_periods"`
	MinDistinctCategories int64       `json:"min_distinct_categories"`
}

func (q *Queries) NewGrade(ctx context.Context, arg NewGradeParams) error {
	_, err := q.db.Exec(ctx, newGrade,
		arg.ID,
		arg.Name,
		arg.MaxBudgetedPeriods,
		arg.MinDistinctCategories,
	)
	return err
}

const nextWindowBoundary = `-- name: NextWindowBoundary :one
SELECT min(t)::TIMESTAMPTZ AS next_boundary
FROM (
	SELECT opens_at AS t FROM grades
	UNION ALL
	SELECT closes_at FROM grades
) b
WHERE t > now()
`

// The next window boundary in the future, over every grade, so the
// realtime layer can arm one timer at it. NULL when no grade has a
// boundary still ahead.
func (q *Queries) NextWindowBoundary(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, nextWindowBoundary)
	var next_boundary pgtype.Timestamptz
	err := row.Scan(&next_boundary)
	return next_boundary, err
}

const openGradeWindowNow = `-- name: OpenGradeWindowNow :one
WITH target AS (
	-- Cast because the domain does not survive inference through the
	-- CTE: without it sqlc types the parameter pgtype.Text, and an
	-- id that is never NULL starts travelling as one that might be.
	SELECT id, closes_at FROM grades WHERE id = $1::entity_id
), updated AS (
	UPDATE grades g SET opens_at = now()
	FROM target t
	WHERE g.id = t.id
		AND (t.closes_at IS NULL OR t.closes_at > now())
	RETURNING g.id
)
SELECT EXISTS (SELECT 1 FROM target) AS found,
	EXISTS (SELECT 1 FROM updated) AS opened
`

type OpenGradeWindowNowRow struct {
	Found  bool `json:"found"`
	Opened bool `json:"opened"`
}

// The two manual levers, as operations of the clock that decides.
//
// The bounds above are instants an administrator chose, so they come
// from the administrator. "Now" is not: it is a reading of a clock,
// and the only clock whose reading matters is the one v_grades.is_open
// is evaluated against. Taken in the browser it was a third clock —
// after the database's and the Go process's — and it arrived rounded
// to the minute, because that is all a datetime-local box carries. Two
// presses inside one minute then wrote closes_at = opens_at and were
// refused by the CHECK, leaving the window open and the administrator
// holding an error about a value they never typed.
//
// Opening leaves closes_at alone. A schedule is a thing an
// administrator set on purpose, and starting a window early is not a
// statement about when it should end; erasing the end would be one,
// made silently. The cost is that a closing time already in the past
// cannot be kept and opened around — the CHECK forbids the row — so
// that case is refused rather than resolved by discarding it. Hence
// two facts, not a row count: no such grade and cannot-open-around are
// different answers and the caller has to tell them apart.
func (q *Queries) OpenGradeWindowNow(ctx context.Context, id string) (OpenGradeWindowNowRow, error) {
	row := q.db.QueryRow(ctx, openGradeWindowNow, id)
	var i OpenGradeWindowNowRow
	err := row.Scan(&i.Found, &i.Opened)
	return i, err
}

const setGradeOrder = `-- name: SetGradeOrder :exec
SELECT set_grade_order($1)
`

func (q *Queries) SetGradeOrder(ctx context.Context, pIds []string) error {
	_, err := q.db.Exec(ctx, setGradeOrder, pIds)
	return err
}

const setGradeRequirements = `-- name: SetGradeRequirements :exec
SELECT set_grade_requirements($1, $2)
`

type SetGradeRequirementsParams struct {
	PGradeID      string `json:"p_grade_id"`
	PRequirements []byte `json:"p_requirements"`
}

func (q *Queries) SetGradeRequirements(ctx context.Context, arg SetGradeRequirementsParams) error {
	_, err := q.db.Exec(ctx, setGradeRequirements, arg.PGradeID, arg.PRequirements)
	return err
}

const setGradeWindow = `-- name: SetGradeWindow :execrows
UPDATE grades SET
	opens_at = CASE WHEN $1::BOOLEAN
		THEN $2::TIMESTAMPTZ ELSE opens_at END,
	closes_at = CASE WHEN $3::BOOLEAN
		THEN $4::TIMESTAMPTZ ELSE closes_at END
WHERE id = $5
`

type SetGradeWindowParams struct {
	SetOpensAt  bool               `json:"set_opens_at"`
	OpensAt     pgtype.Timestamptz `json:"opens_at"`
	SetClosesAt bool               `json:"set_closes_at"`
	ClosesAt    pgtype.Timestamptz `json:"closes_at"`
	ID          string             `json:"id"`
}

// Each bound is written only if the caller named it.
//
// Not both-or-neither, because the two boxes on the card are edited
// separately and by different people. An administrator setting the
// closing date would otherwise send back whatever opening time their
// page was built with, which is not what the grade has if somebody
// else moved it since — and nobody would see it happen, because the
// write succeeds and restores a value that had genuinely been there.
//
// NULL is a value here ("no such bound"), so absence cannot be spelt
// as NULL and needs a flag of its own.
func (q *Queries) SetGradeWindow(ctx context.Context, arg SetGradeWindowParams) (int64, error) {
	result, err := q.db.Exec(ctx, setGradeWindow,
		arg.SetOpensAt,
		arg.OpensAt,
		arg.SetClosesAt,
		arg.ClosesAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setMaxBudgetedPeriods = `-- name: SetMaxBudgetedPeriods :exec
SELECT set_max_budgeted_periods($1,
	$2, $3)
`

type SetMaxBudgetedPeriodsParams struct {
	GradeID            string      `json:"grade_id"`
	MaxBudgetedPeriods pgtype.Int8 `json:"max_budgeted_periods"`
	Accept             []string    `json:"accept"`
}

func (q *Queries) SetMaxBudgetedPeriods(ctx context.Context, arg SetMaxBudgetedPeriodsParams) error {
	_, err := q.db.Exec(ctx, setMaxBudgetedPeriods, arg.GradeID, arg.MaxBudgetedPeriods, arg.Accept)
	return err
}

const updateGradeSettings = `-- name: UpdateGradeSettings :execrows
UPDATE grades
SET name = $2, min_distinct_categories = $3
WHERE id = $1
`

type UpdateGradeSettingsParams struct {
	ID                    string `json:"id"`
	Name                  string `json:"name"`
	MinDistinctCategories int64  `json:"min_distinct_categories"`
}

// The two fields of a grade that are no rule's input, written
// together because they are one form and one save. Two statements
// would be two transactions on the pool: the first could land, the
// second fail, and the response would report failure for an edit that
// half happened.
func (q *Queries) UpdateGradeSettings(ctx context.Context, arg UpdateGradeSettingsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateGradeSettings, arg.ID, arg.Name, arg.MinDistinctCategories)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
