// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type LegalSex string

const (
	LegalSexF LegalSex = "F"
	LegalSexM LegalSex = "M"
	LegalSexX LegalSex = "X"
)

func (e *LegalSex) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LegalSex(s)
	case string:
		*e = LegalSex(s)
	default:
		return fmt.Errorf("unsupported scan type for LegalSex: %T", src)
	}
	return nil
}

type NullLegalSex struct {
	LegalSex LegalSex `json:"legal_sex"`
	Valid    bool     `json:"valid"` // Valid is true if LegalSex is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLegalSex) Scan(value interface{}) error {
	if value == nil {
		ns.LegalSex, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LegalSex.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLegalSex) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LegalSex), nil
}

type Category struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Course struct {
	ID           string      `json:"id"`
	Name         string      `json:"name"`
	Description  string      `json:"description"`
	MaxStudents  pgtype.Int8 `json:"max_students"`
	InviteOnly   bool        `json:"invite_only"`
	Teacher      string      `json:"teacher"`
	TeacherEmail string      `json:"teacher_email"`
	Location     string      `json:"location"`
	Term         string      `json:"term"`
	Cost         string      `json:"cost"`
	CategoryID   string      `json:"category_id"`
}

type CourseAllowedGrade struct {
	CourseID string `json:"course_id"`
	GradeID  string `json:"grade_id"`
}

type CourseAllowedLegalSex struct {
	CourseID string   `json:"course_id"`
	LegalSex LegalSex `json:"legal_sex"`
}

type CoursePeriod struct {
	CourseID string `json:"course_id"`
	PeriodID string `json:"period_id"`
}

type Enrollment struct {
	StudentID          string `json:"student_id"`
	CourseID           string `json:"course_id"`
	StudentDroppable   bool   `json:"student_droppable"`
	CountsTowardBudget bool   `json:"counts_toward_budget"`
}

type Grade struct {
	ID                    string             `json:"id"`
	Name                  string             `json:"name"`
	OpensAt               pgtype.Timestamptz `json:"opens_at"`
	ClosesAt              pgtype.Timestamptz `json:"closes_at"`
	MaxBudgetedPeriods    pgtype.Int8        `json:"max_budgeted_periods"`
	MinDistinctCategories int64              `json:"min_distinct_categories"`
	SortOrder             int64              `json:"sort_order"`
}

type GradeRequirementGroup struct {
	ID             int64  `json:"id"`
	GradeID        string `json:"grade_id"`
	MinPeriodCount int64  `json:"min_period_count"`
}

type GradeRequirementGroupCategory struct {
	RequirementCategoryID int64  `json:"requirement_category_id"`
	CategoryID            string `json:"category_id"`
}

type Period struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	SortOrder int64  `json:"sort_order"`
}

type SchemaVersion struct {
	Singleton bool  `json:"singleton"`
	Version   int64 `json:"version"`
}

type Student struct {
	ID       string   `json:"id"`
	Name     string   `json:"name"`
	GradeID  string   `json:"grade_id"`
	LegalSex LegalSex `json:"legal_sex"`
}

type VCourse struct {
	ID                string      `json:"id"`
	Name              string      `json:"name"`
	Description       string      `json:"description"`
	CategoryID        string      `json:"category_id"`
	Teacher           string      `json:"teacher"`
	TeacherEmail      string      `json:"teacher_email"`
	Location          string      `json:"location"`
	Term              string      `json:"term"`
	Cost              string      `json:"cost"`
	MaxStudents       pgtype.Int8 `json:"max_students"`
	InviteOnly        bool        `json:"invite_only"`
	CurrentStudents   int64       `json:"current_students"`
	PeriodIds         []string    `json:"period_ids"`
	AllowedLegalSexes []LegalSex  `json:"allowed_legal_sexes"`
	AllowedGradeIds   []string    `json:"allowed_grade_ids"`
}

type VEnrollment struct {
	StudentID          string `json:"student_id"`
	StudentName        string `json:"student_name"`
	GradeID            string `json:"grade_id"`
	CourseID           string `json:"course_id"`
	CourseName         string `json:"course_name"`
	StudentDroppable   bool   `json:"student_droppable"`
	CountsTowardBudget bool   `json:"counts_toward_budget"`
}

type VExportEnrollment struct {
	StudentID          string      `json:"student_id"`
	StudentName        string      `json:"student_name"`
	GradeID            string      `json:"grade_id"`
	LegalSex           LegalSex    `json:"legal_sex"`
	CourseID           string      `json:"course_id"`
	CourseName         string      `json:"course_name"`
	Term               string      `json:"term"`
	PeriodID           interface{} `json:"period_id"`
	PeriodSortOrder    pgtype.Int8 `json:"period_sort_order"`
	StudentDroppable   bool        `json:"student_droppable"`
	CountsTowardBudget bool        `json:"counts_toward_budget"`
}

type VGrade struct {
	ID                    string             `json:"id"`
	Name                  string             `json:"name"`
	OpensAt               pgtype.Timestamptz `json:"opens_at"`
	ClosesAt              pgtype.Timestamptz `json:"closes_at"`
	IsOpen                pgtype.Bool        `json:"is_open"`
	MaxBudgetedPeriods    pgtype.Int8        `json:"max_budgeted_periods"`
	MinDistinctCategories int64              `json:"min_distinct_categories"`
	SortOrder             int64              `json:"sort_order"`
}

type VGradeRequirement struct {
	ID             int64    `json:"id"`
	GradeID        string   `json:"grade_id"`
	MinPeriodCount int64    `json:"min_period_count"`
	CategoryIds    []string `json:"category_ids"`
}

type VStudentRequirement struct {
	StudentID             string `json:"student_id"`
	GradeID               string `json:"grade_id"`
	RequirementCategoryID int64  `json:"requirement_category_id"`
	MinPeriodCount        int64  `json:"min_period_count"`
	SatisfiedPeriods      int64  `json:"satisfied_periods"`
	Met                   bool   `json:"met"`
}

type VStudentStatus struct {
	StudentID              string      `json:"student_id"`
	StudentName            string      `json:"student_name"`
	GradeID                string      `json:"grade_id"`
	BudgetedPeriodsUsed    int64       `json:"budgeted_periods_used"`
	MaxBudgetedPeriods     pgtype.Int8 `json:"max_budgeted_periods"`
	DistinctCategoriesUsed int64       `json:"distinct_categories_used"`
	MinDistinctCategories  int64       `json:"min_distinct_categories"`
}
