// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: periods.sql

package db

import (
	"context"
)

const deletePeriod = `-- name: DeletePeriod :execrows
DELETE FROM periods WHERE id = $1
`

func (q *Queries) DeletePeriod(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deletePeriod, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPeriods = `-- name: GetPeriods :many
SELECT id, name, sort_order FROM periods ORDER BY sort_order, id
`

func (q *Queries) GetPeriods(ctx context.Context) ([]Period, error) {
	rows, err := q.db.Query(ctx, getPeriods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Period
	for rows.Next() {
		var i Period
		if err := rows.Scan(&i.ID, &i.Name, &i.SortOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newPeriod = `-- name: NewPeriod :exec
INSERT INTO periods (id, name, sort_order)
SELECT $1, $2, COALESCE(MAX(sort_order), 0) + 1
FROM periods
`

type NewPeriodParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) NewPeriod(ctx context.Context, arg NewPeriodParams) error {
	_, err := q.db.Exec(ctx, newPeriod, arg.ID, arg.Name)
	return err
}

const renamePeriod = `-- name: RenamePeriod :execrows
UPDATE periods SET name = $2 WHERE id = $1
`

type RenamePeriodParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) RenamePeriod(ctx context.Context, arg RenamePeriodParams) (int64, error) {
	result, err := q.db.Exec(ctx, renamePeriod, arg.ID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setPeriodOrder = `-- name: SetPeriodOrder :exec
SELECT set_period_order($1)
`

func (q *Queries) SetPeriodOrder(ctx context.Context, pIds []string) error {
	_, err := q.db.Exec(ctx, setPeriodOrder, pIds)
	return err
}
