// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schema_version.sql

package db

import (
	"context"
)

const getSchemaVersion = `-- name: GetSchemaVersion :one
SELECT version FROM schema_version WHERE singleton
`

// The application refuses to start against a schema it does not
// expect; this is the read behind that check and behind /healthz.
func (q *Queries) GetSchemaVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getSchemaVersion)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const readyProbe = `-- name: ReadyProbe :one
SELECT
	(SELECT version FROM schema_version WHERE singleton) AS version,
	EXISTS (SELECT 1 FROM v_grades) AS has_grades,
	EXISTS (SELECT 1 FROM v_grade_requirements) AS has_grade_requirements,
	EXISTS (SELECT 1 FROM v_courses) AS has_courses,
	EXISTS (SELECT 1 FROM v_enrollments) AS has_enrollments,
	EXISTS (SELECT 1 FROM v_student_status) AS has_student_status,
	EXISTS (SELECT 1 FROM v_student_requirements) AS has_student_requirements,
	EXISTS (SELECT 1 FROM v_export_enrollments) AS has_export_enrollments
`

type ReadyProbeRow struct {
	Version                int64 `json:"version"`
	HasGrades              bool  `json:"has_grades"`
	HasGradeRequirements   bool  `json:"has_grade_requirements"`
	HasCourses             bool  `json:"has_courses"`
	HasEnrollments         bool  `json:"has_enrollments"`
	HasStudentStatus       bool  `json:"has_student_status"`
	HasStudentRequirements bool  `json:"has_student_requirements"`
	HasExportEnrollments   bool  `json:"has_export_enrollments"`
}

// The same version, plus proof that the objects requests actually go
// through are there.
//
// The version on its own is a claim the schema makes about itself, not
// an observation of it, and the two came apart in exactly the way that
// matters: dropping v_courses and leaving schema_version alone gave a
// process that started, stayed up, answered /readyz with "ready", and
// served 500s to every student — so a load balancer held it in
// rotation indefinitely and nothing escalated. A half-applied
// migration is that state, and the morning of selection is when
// migrations are applied.
//
// Each EXISTS stops at the first row, so this costs a row from each
// view rather than a scan of it. The rows are not the point: the point
// is that the statement cannot plan unless every view, and everything
// each view is built on, is present.
func (q *Queries) ReadyProbe(ctx context.Context) (ReadyProbeRow, error) {
	row := q.db.QueryRow(ctx, readyProbe)
	var i ReadyProbeRow
	err := row.Scan(
		&i.Version,
		&i.HasGrades,
		&i.HasGradeRequirements,
		&i.HasCourses,
		&i.HasEnrollments,
		&i.HasStudentStatus,
		&i.HasStudentRequirements,
		&i.HasExportEnrollments,
	)
	return i, err
}
