// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: students.sql

package db

import (
	"context"
)

const deleteStudent = `-- name: DeleteStudent :execrows
DELETE FROM students WHERE id = $1
`

func (q *Queries) DeleteStudent(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStudent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getStudentRequirements = `-- name: GetStudentRequirements :many
SELECT student_id, grade_id, requirement_category_id, min_period_count, satisfied_periods, met FROM v_student_requirements ORDER BY student_id, requirement_category_id
`

func (q *Queries) GetStudentRequirements(ctx context.Context) ([]VStudentRequirement, error) {
	rows, err := q.db.Query(ctx, getStudentRequirements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VStudentRequirement
	for rows.Next() {
		var i VStudentRequirement
		if err := rows.Scan(
			&i.StudentID,
			&i.GradeID,
			&i.RequirementCategoryID,
			&i.MinPeriodCount,
			&i.SatisfiedPeriods,
			&i.Met,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentRequirementsByID = `-- name: GetStudentRequirementsByID :many
SELECT student_id, grade_id, requirement_category_id, min_period_count, satisfied_periods, met FROM v_student_requirements
WHERE student_id = $1
ORDER BY requirement_category_id
`

func (q *Queries) GetStudentRequirementsByID(ctx context.Context, studentID string) ([]VStudentRequirement, error) {
	rows, err := q.db.Query(ctx, getStudentRequirementsByID, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VStudentRequirement
	for rows.Next() {
		var i VStudentRequirement
		if err := rows.Scan(
			&i.StudentID,
			&i.GradeID,
			&i.RequirementCategoryID,
			&i.MinPeriodCount,
			&i.SatisfiedPeriods,
			&i.Met,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentStatus = `-- name: GetStudentStatus :many
SELECT student_id, student_name, grade_id, budgeted_periods_used, max_budgeted_periods, distinct_categories_used, min_distinct_categories FROM v_student_status ORDER BY student_id
`

func (q *Queries) GetStudentStatus(ctx context.Context) ([]VStudentStatus, error) {
	rows, err := q.db.Query(ctx, getStudentStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VStudentStatus
	for rows.Next() {
		var i VStudentStatus
		if err := rows.Scan(
			&i.StudentID,
			&i.StudentName,
			&i.GradeID,
			&i.BudgetedPeriodsUsed,
			&i.MaxBudgetedPeriods,
			&i.DistinctCategoriesUsed,
			&i.MinDistinctCategories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentStatusByID = `-- name: GetStudentStatusByID :one
SELECT student_id, student_name, grade_id, budgeted_periods_used, max_budgeted_periods, distinct_categories_used, min_distinct_categories FROM v_student_status WHERE student_id = $1
`

func (q *Queries) GetStudentStatusByID(ctx context.Context, studentID string) (VStudentStatus, error) {
	row := q.db.QueryRow(ctx, getStudentStatusByID, studentID)
	var i VStudentStatus
	err := row.Scan(
		&i.StudentID,
		&i.StudentName,
		&i.GradeID,
		&i.BudgetedPeriodsUsed,
		&i.MaxBudgetedPeriods,
		&i.DistinctCategoriesUsed,
		&i.MinDistinctCategories,
	)
	return i, err
}

const getStudents = `-- name: GetStudents :many
SELECT id, name, grade_id, legal_sex FROM students ORDER BY id
`

func (q *Queries) GetStudents(ctx context.Context) ([]Student, error) {
	rows, err := q.db.Query(ctx, getStudents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GradeID,
			&i.LegalSex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStudents = `-- name: UpsertStudents :exec
SELECT upsert_students($1, $2, $3, $4, $5)
`

type UpsertStudentsParams struct {
	PIds        []string `json:"p_ids"`
	PNames      []string `json:"p_names"`
	PGradeIds   []string `json:"p_grade_ids"`
	PLegalSexes []string `json:"p_legal_sexes"`
	PAccept     []string `json:"p_accept"`
}

func (q *Queries) UpsertStudents(ctx context.Context, arg UpsertStudentsParams) error {
	_, err := q.db.Exec(ctx, upsertStudents,
		arg.PIds,
		arg.PNames,
		arg.PGradeIds,
		arg.PLegalSexes,
		arg.PAccept,
	)
	return err
}
